
title: grtnr.ai
email: till.gartner@gmail.com
description: My AI playground
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grtnr.ai" # the base hostname & protocol for your site, e.g. http://example.com
#show_downloads: "false"
twitter_username: tillg
github_username:  tillg

# Cayman theme specific
github:
  # Remove button "View on Github"
  is_project_page: false

# Build settings
#theme: minima # minimal-mistakes-jekyll
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
 #- jekyll-postfiles


permalink: /:year-:month-:day-:title.html