
title: grtnr.ai
email: till.gartner@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My AI playground
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grtnr.ai" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tillg
github_username:  tillg


# Build settings
#theme: minima # minimal-mistakes-jekyll
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
 #- jekyll-postfiles


permalink: /:year-:month-:day-:title.html